spring:
  cloud:
    aws:
      credentials:
        secret-key: #Your secret key
        access-key: #Your access key
      region:
        static: #Your region

aws:
  access-key: #Your access key
  secret-key: #Your secret key
  region: #Your region
  dynamo-table-name: #DynamoDb table name
