spring:

  application:

    name: trainer-workload-service

  activemq:

    broker-url: "tcp://localhost:61616"
    user: admin
    password: your_secure_password

  data:

    redis:
      host: localhost
      port: 6379
      ttl: 3 #Time to live in minutes

    mongodb:
      uri: mongodb://admin:your_secure_password@localhost:27017/trainer-workload?authSource=admin
      auto-index-creation: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8081