spring:
  application:
    name: trainer-workload-service
  config:
    import:
      - "classpath:application-aws-confidential.yml"
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3 #Time to live in minutes
  cloud:
    aws:
      sqs:
        enabled: true
        endpoint: https://sqs.us-east-1.amazonaws.com
      dynamodb:
        table-prefix: ""
        table-suffix: ""

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false

server:
  port: 8081