spring:
  cache:
    type: simple
  application:
    name: trainer-workload-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    discovery:
      enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb

server:
  port: 8081

eureka:
  client:
    enabled: false